NumPy  Date:05/06/2025

1.Create a 1D array from a list.


In [3]:
import numpy as np
import pandas as pd

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


2. Create a 3x3 array of zeros.


In [6]:
z = np.zeros((3, 3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3. Create a 2x2 array of ones.

In [7]:
ones_array=np.ones((2, 2))
print(ones_array)

[[1. 1.]
 [1. 1.]]


4. Generate array from 0 to 10 (exclusive).

In [70]:
arr = np.arange(0, 10)  
print(arr)

[0 1 2 3 4 5 6 7 8 9]


5. Create 5 evenly spaced numbers between 0 and 1.


In [ ]:
arr = np.linspace(0, 1, 5) 
print(arr)

[0.   0.25 0.5  0.75 1.  ]


6. Create a 4x4 identity matrix.

In [13]:
identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


7. Reshape 1D array to 2D.

In [62]:
arr = np.array([1, 2, 3, 4, 5, 9])
print(arr)
reshaped_array = arr.reshape(3,2)
print(" Reshaped array:\n", reshaped_array)

[1 2 3 4 5 9]
 Reshaped array:
 [[1 2]
 [3 4]
 [5 9]]


8. Get the shape and dtype of an array.

In [49]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print("Shape:", arr.shape)
print("Dtype:", arr.dtype)

[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dtype: int32


9. Reverse a NumPy array.

In [ ]:
arr= np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]
print("Reversed array:", reversed_arr)

Reversed array: [5 4 3 2 1]


10. Extract even numbers from an array.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_numbers = arr[arr % 2 == 0]
print("Even numbers:", even_numbers)

Even numbers: [ 2  4  6  8 10]


11. Find the max in each row.

In [65]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
max = arr.max(axis=1)
print("Max in each row:", max)

Max in each row: [3 6 9]


12. Compute the mean, std, and median of an array.


In [89]:
arr = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(arr)
std_value = np.std(arr)
median_value = np.median(arr)
print("Mean:", mean_value)
print("Standard Deviation:", std_value) 
print("Median:", median_value)

Mean: 3.0
Standard Deviation: 1.4142135623730951
Median: 3.0


13. Stack two arrays vertically.

In [76]:
#1D Array
arr1= np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
stack_arr= np.stack((arr1, arr2), axis=1) 
print("Stacked array:\n", stack_arr)

Stacked array:
 [[1 4]
 [2 5]
 [3 6]]


14. Stack two arrays horizontally.

In [77]:
#2D array
arr1= np.array([[1, 2, 3],[4, 5, 6]])
arr2 = np.array([[7, 8, 9],[10, 11, 12]])
stack_arr= np.stack((arr1, arr2), axis=1) 
print("Stacked array:\n", stack_arr)

Stacked array:
 [[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]


15. Stack two arrays horizontally.


In [79]:
# 15. Stack two arrays horizontally.
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
stacked_arr = np.stack((arr1, arr2), axis=0)
print("Stacked array:\n", stacked_arr)

Stacked array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


16. Find the unique values and their counts.


In [83]:
# 16. Find the unique values and their counts.
arr = np.array([0, 1, 2, 2, 4, 4, 4, 5, 6, 7, 7])
print("Original array:", arr)
unique, counts = np.unique(arr, return_counts=True)
print("Unique values:", unique)
print("Counts:", counts)  

Original array: [0 1 2 2 4 4 4 5 6 7 7]
Unique values: [0 1 2 4 5 6 7]
Counts: [1 1 2 3 1 1 2]


17. Replace NaN with column means.


In [95]:
arr = np.array([[1, 2, np.nan], [4, 5, 6], [7, np.nan, 9]])
print("Original array with NaN values:\n", arr)
print("Array without NaN values with coulumn means:\n", np.where(np.isnan(arr), np.nanmean(arr, axis=0), arr))

Original array with NaN values:
 [[ 1.  2. nan]
 [ 4.  5.  6.]
 [ 7. nan  9.]]
Array without NaN values with coulumn means:
 [[1.  2.  7.5]
 [4.  5.  6. ]
 [7.  3.5 9. ]]


18. Get index of min and max values.


In [100]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

min_value=np.argmin(arr)
max_value=np.argmax(arr)
print("Index of minimum value:", min_value)
print("Index of maximum value:", max_value)

[[1 2 3]
 [4 5 6]]
Index of minimum value: 0
Index of maximum value: 5


19. Create a 3D array of random integers.



In [ ]:
arr = np.random.randint(0, 10, (2, 3, 4)) 
print("3D array of random integers:\n", arr)

3D array of random integers:
 [[[7 8 9 4]
  [6 1 4 7]
  [8 9 6 0]]

 [[3 6 0 9]
  [1 4 0 4]
  [2 6 1 6]]]


20. Use np.where() to replace values


In [103]:
# 20. Use np.where() to replace values
arr = np.array([1, 2, 3, 4, 5])
print("Original array:", arr)
# Replace values greater than 3 with 0
arr_replaced = np.where(arr > 3, 0, arr)    
print("Array after replacement:\n", arr_replaced)

Original array: [1 2 3 4 5]
Array after replacement:
 [1 2 3 0 0]


Pandas

1. Create a Series using a Python list.


In [106]:
import pandas as pd
s=pd.Series([22,33,44,55,66])
print(s)

0    22
1    33
2    44
3    55
4    66
dtype: int64


2. Create a Series with custom string indices.




In [107]:
s = pd.Series([22, 33, 44, 55, 66], index=['a', 'b', 'c', 'd', 'e'])
print(s)

a    22
b    33
c    44
d    55
e    66
dtype: int64


3. Create a Series from a dictionary.


In [109]:
dict = {'a': 22, 'b': 33, 'c': 44, 'd': 55, 'e': 66}
s = pd.Series(dict)
print(s)

a    22
b    33
c    44
d    55
e    66
dtype: int64


4. Access first 3 elements of a Series.


In [115]:
# 4. Access first 3 elements of a Series.
s = pd.Series([22, 33, 44, 55, 66])
print("First 3 elements of the Series:\n", s.head(3)) 

First 3 elements of the Series:
 0    22
1    33
2    44
dtype: int64


5. Filter Series elements greater than 50.



In [116]:
s = pd.Series([22, 33, 44, 55, 66])
filtered_series = s[s > 50]
print("Filtered Series (elements > 50):\n", filtered_series)

Filtered Series (elements > 50):
 3    55
4    66
dtype: int64


6. Add two Series with different indices.



In [123]:
s1 = pd.Series([2, 3, 5])
s2 = pd.Series([5, 6, 7, 8, 10, 11])
result = s1.add(s2,fill_value=0)
print("Result of addition:\n", result)

Result of addition:
 0     7.0
1     9.0
2    12.0
3     8.0
4    10.0
5    11.0
dtype: float64



7. Multiply a Series by a scalar.


In [4]:
# Multiply a Series by a scalar.
s = pd.Series([1, 2, 3, 4, 5])
scalar = 3
result = s * scalar
print("Result of multiplication by scalar:\n", result)

Result of multiplication by scalar:
 0     3
1     6
2     9
3    12
4    15
dtype: int64


8. Use .multiply() method to multiply with scalar.


In [6]:
# 8. Use .multiply() method to multiply with scalar.
s = pd.Series( [4, 5, 6, 7, 8])
print("Original Series:\n", s)
scalar = 3
result = s.multiply(scalar)
print("Result of multiplication using .multiply() method:\n", result)

Original Series:
 0    4
1    5
2    6
3    7
4    8
dtype: int64
Result of multiplication using .multiply() method:
 0    12
1    15
2    18
3    21
4    24
dtype: int64


10. Sort Series by values descending.


In [12]:
# 10. Sort Series by values descending.
s = pd.Series([22, 33, 77, 55, 66])
sorted_series = s.sort_values(ascending=False)
print("Sorted Series in descending order:\n", sorted_series)

Sorted Series in descending order:
 2    77
4    66
3    55
1    33
0    22
dtype: int64


11. Sort Series by index.


In [13]:
s = pd.Series([22, 33, 44, 55, 66], index=['e', 'd', 'c', 'b', 'a'])
sorted_series = s.sort_index()
print("Sorted Series by index:\n", sorted_series)

Sorted Series by index:
 a    66
b    55
c    44
d    33
e    22
dtype: int64


12. Check for null values.



In [17]:
s = pd.Series([22, np.nan, 44, 55, np.nan, 66])
print("Original Series with NaN values:\n", s)
null_check = s.isnull()
print("Check for null values:\n", null_check)

Original Series with NaN values:
 0    22.0
1     NaN
2    44.0
3    55.0
4     NaN
5    66.0
dtype: float64
Check for null values:
 0    False
1     True
2    False
3    False
4     True
5    False
dtype: bool


14. Concatenate two Series using concat().


In [19]:
s1 = pd.Series([1, 2, 3])
s2 = pd.Series([4, 5, 6])
result = pd.concat([s1, s2])
print("Concatenated Series:\n", result)

Concatenated Series:
 0    1
1    2
2    3
0    4
1    5
2    6
dtype: int64


15. Concatenate two Series using append().


In [81]:
s1 = pd.Series([1, 2, 3])
s2 = pd.Series([4, 5, 6])
result = s1.append(s2)
print("Concatenated Series:\n", result)

AttributeError: 'Series' object has no attribute 'append'

16. Retrieve first 5 elements using .head()



In [77]:
s = pd.Series([22, 33, 44, 55, 66, 77, 88])
first_five = s.head(5)
print("First five elements of the Series:\n", first_five)

First five elements of the Series:
 0    22
1    33
2    44
3    55
4    66
dtype: int64


17. Retrieve last 5 elements using .tail()


In [80]:
s = pd.Series([22, 33, 44, 55, 66, 77, 88])
last_five = s.tail(5)
print("Last five elements of the Series:\n", last_five)

Last five elements of the Series:
 2    44
3    55
4    66
5    77
6    88
dtype: int64


18. Convert Series to DataFrame.


In [56]:
s = pd.Series({'Frodo': 23, 'Gandalf': 45, 'Legolas': 33, 'Elrond': 50, 'Aragorn': 40})
df = s.to_frame(name='Age')
print("DataFrame created from Series:\n", df)

DataFrame created from Series:
          Age
Frodo     23
Gandalf   45
Legolas   33
Elrond    50
Aragorn   40


19. Replace NaN with 0.


In [57]:
s = pd.Series([22, np.nan, np.nan, 55, np.nan, 66])
print("Original Series with NaN values:\n", s)
s_filled = s.fillna(0)
print("Series after replacing NaN with 0:\n", s_filled)

Original Series with NaN values:
 0    22.0
1     NaN
2     NaN
3    55.0
4     NaN
5    66.0
dtype: float64
Series after replacing NaN with 0:
 0    22.0
1     0.0
2     0.0
3    55.0
4     0.0
5    66.0
dtype: float64


20. Drop missing values.


In [42]:
s = pd.Series(['Haweye', np.nan,'Shang-chi','Nebula', np.nan,'Gamora'])
print("Original Series with NaN values:\n", s)  
s_dropped = s.dropna()
print("Series after dropping NaN values:\n", s_dropped)

Original Series with NaN values:
 0       Haweye
1          NaN
2    Shang-chi
3       Nebula
4          NaN
5       Gamora
dtype: object
Series after dropping NaN values:
 0       Haweye
2    Shang-chi
3       Nebula
5       Gamora
dtype: object


21. Check Series data type.



In [76]:
s1= pd.Series([22, 33, 44, 66])
s2 = pd.Series([2.2, 3.3, 4.4, 6.6])
s3= pd.Series([np.nan, np.nan, np.nan, np.nan])
s4=pd.Series(['Alex','Bob', 'Charlie', 'David'])

print("Data type of the Series s1:", s1.dtype)
print("Data type of the Series s2:", s2.dtype)
print("Data type of the Series s3:", s3.dtype)
print("Data type of the Series s4:", s4.dtype)

Data type of the Series s1: int64
Data type of the Series s2: float64
Data type of the Series s3: float64
Data type of the Series s4: object


~ Padma Rani Nayak ~